- name: Install service based on instance role
  hosts: eliza

  vars:
    role: eliza

    git_repo: 'git@github.com:icekernel/hashistack-role-{{ role }}.git'
    srv_base_dir: /srv/{{ role }}
    git_repo_dest: '{{ srv_base_dir }}/{{ role }}.git'
    checkout_dest: '{{ srv_base_dir }}/{{ role }}'
    owner: '{{ role }}'
    group: '{{ role }}'
    key_file: /home/{{ role }}/.ssh/{{ role }}-checkout.pem

  tasks:
    - name: Debug the current role
      ansible.builtin.debug:
        var: role

    - ansible.builtin.import_tasks:
        file: ./tasks/hosting-user.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/install-node.yml

    - ansible.builtin.import_tasks:
        file: ./tasks/docker-requirements.yml

    # we're now building custom repositories in the pull service

    # - name: Clone service's git repository
    #   ansible.builtin.import_tasks: ./tasks/clone-repository.yml

    # - import_tasks: ./tasks/setup-eliza.yml
