- name: Install service based on instance role
  hosts: eliza

  vars:
    role: eliza

    git_repo: 'git@github.com:Use-Prism/{{ role }}.git'
    srv_base_dir: /srv/{{ role }}
    git_repo_dest: '{{ srv_base_dir }}/{{ role }}.git'
    checkout_dest: '{{ srv_base_dir }}/{{ role }}'
    owner: '{{ role }}'
    group: '{{ role }}'
    key_file: /home/{{ role }}/.ssh/{{ role }}-checkout.pem

  tasks:
    - amazon.aws.ec2_metadata_facts:
      register: meta

    - set_fact:
        role: '{{ meta.ansible_facts.ansible_ec2_tags_instance_Role }}'

    - name: Shut down docker-compose
      ansible.builtin.shell: docker-compose down
      args:
        chdir: /home/eliza
      become: true

    - import_tasks: ../../pull/tasks/pull-eliza-once.yml
