---
- name: Configure host for ansible-pull
  hosts: all

  vars:
    ansible_pull_repo: git@github.com:Use-Prism/eliza-infra.git

  tasks:
    - name: Install GitHub infra repo private ssh key
      ansible.builtin.copy:
        src: prism-eliza-20250127.pem
        dest: /home/ubuntu/.ssh/id_rsa
        mode: 0600

    - name: Ensure python3-virtualenv installed
      ansible.builtin.apt:
        name: python3-virtualenv
        state: present
      become: true

    - name: Create venv
      ansible.builtin.pip:
        name: '{{ item }}'
        virtualenv: /opt/ansible.venv
      with_items:
        - ansible
        - boto3
      become: true

    - name: Template ansible-pull.sh
      ansible.builtin.template:
        src: ./templates/ansible-pull.sh.j2
        dest: /home/ubuntu/ansible-pull.sh
        mode: 0755

    - name: Set cron for ansible pull
      ansible.builtin.cron:
        name: ansible pull
        minute: '{{ 60 | random(seed=inventory_hostname) }}'
        job: '/home/ubuntu/ansible-pull.sh 2>&1 | systemd-cat -t ansible-pull -p info'
        user: ubuntu

    - name: Create oneshot systemd unit for ansible pull
      ansible.builtin.copy:
        dest: /etc/systemd/system/ansible-pull.service
        mode: 0644
        content: |
          [Unit]
          Description=ansible-pull service
          Requires=network-online.target
          After=consul.service

          [Service]
          Type=oneshot
          ExecStart=/home/ubuntu/ansible-pull.sh
          User=ubuntu
          RemainAfterExit=true
          TimeoutStartSec=0

          [Install]
          WantedBy=multi-user.target
      become: true

    - name: Enable ansible-pull service
      ansible.builtin.systemd:
        name: ansible-pull
        enabled: yes
        daemon_reload: yes
      become: true
