---
- name: Install hashistack packages
  hosts: bastion
  tasks:
    - name: Import hashistack packages
      ansible.builtin.import_tasks: ./tasks/hashistack-packages.yml

- name: Consul base configuration
  hosts: bastion
  tasks:
    - name: Import consul base configurations
      ansible.builtin.import_tasks: ./tasks/consul-base.yml

- name: Consul server configuration
  hosts: bastion

  vars:
    CONSUL_DOMAIN: 'consul'

  tasks:
    - name: Copy consul server cert
      ansible.builtin.copy:
        dest: '/etc/consul.d/{{ CONSUL_DATACENTER }}-server-{{ CONSUL_DOMAIN }}-latest.pem'
        src: './files/consul/{{ CONSUL_DATACENTER }}-server-{{ CONSUL_DOMAIN }}-latest.pem'
        mode: '0644'
      become: true

    - name: Copy consul server key
      ansible.builtin.copy:
        dest: '/etc/consul.d/{{ CONSUL_DATACENTER }}-server-{{ CONSUL_DOMAIN }}-latest-key.pem'
        src: './files/consul/{{ CONSUL_DATACENTER }}-server-{{ CONSUL_DOMAIN }}-latest-key.pem'
        mode: '0644'
      become: true

    - name: Template consul server.hcl
      ansible.builtin.template:
        src: ./templates/consul/server.hcl.j2
        dest: /etc/consul.d/server.hcl
        mode: '0644'
      become: true

- name: Nomad base configuration
  hosts: bastion
  tasks:
    - name: Import nomad base configurations
      ansible.builtin.import_tasks: ./tasks/nomad-base.yml

- name: Nomad server configuration
  hosts: bastion
  tasks:
    - name: Copy nomad server cert
      ansible.builtin.copy:
        dest: '/etc/nomad.d/{{ ENVIRONMENT }}-server.pem'
        src: './files/nomad/{{ ENVIRONMENT }}-server.pem'
        mode: '0644'
      become: true

    - name: Copy nomad server key
      ansible.builtin.copy:
        dest: '/etc/nomad.d/{{ ENVIRONMENT }}-server-key.pem'
        src: './files/nomad/{{ ENVIRONMENT }}-server-key.pem'
        mode: '0644'
      become: true

    - name: Copy nomad cli cert key
      ansible.builtin.copy:
        dest: '/etc/nomad.d/{{ ENVIRONMENT }}-cli-key.pem'
        src: './files/nomad/{{ ENVIRONMENT }}-cli-key.pem'
        mode: '0644'
      become: true

    - name: Copy nomad cli cert
      ansible.builtin.copy:
        dest: '/etc/nomad.d/{{ ENVIRONMENT }}-cli.pem'
        src: './files/nomad/{{ ENVIRONMENT }}-cli.pem'
        mode: '0644'
      become: true

    - name: Template nomad bash profile in /etc/profile.d
      ansible.builtin.template:
        src: ./templates/nomad/nomad-bash-profile.j2
        dest: /etc/profile.d/nomad.sh
        mode: '0644'
      become: true

    - name: Touch the nomad acl file
      ansible.builtin.copy:
        dest: /etc/profile.d/nomad_acl.sh
        content: ''
        mode: '0644'
      become: true

    - name: Template nomad server.hcl
      ansible.builtin.template:
        src: ./templates/nomad/server.hcl.j2
        dest: /etc/nomad.d/server.hcl
        mode: '0644'
      become: true
      vars:
        nomad_gossip_key: "{{ lookup('file', './files/nomad/' + ENVIRONMENT + '-gossip.key') }}"

- name: Nomad jobs
  hosts: bastion

  tasks:
    - name: Import nomad jobs
      ansible.builtin.import_tasks: ./tasks/nomad-jobs.yml

    - name: Add memory oversubscription command to Nomad unit
      ansible.builtin.copy:
        dest: /opt/nomad-execstartpost.sh
        content: |
          #!/bin/sh
          . /etc/profile.d/nomad.sh
          . /etc/profile.d/nomad_acl.sh
          while ! curl -k -s --fail -H "X-Nomad-Token: ${NOMAD_TOKEN}" $NOMAD_ADDR/v1/status/leader; do sleep 1; done
          curl -k -s -H "X-Nomad-Token: ${NOMAD_TOKEN}" $NOMAD_ADDR/v1/operator/scheduler/configuration \
          | jq '.SchedulerConfig | .MemoryOversubscriptionEnabled=true' \
          | curl -k -X PUT -H "X-Nomad-Token: ${NOMAD_TOKEN}" $NOMAD_ADDR/v1/operator/scheduler/configuration -d @-
        mode: '0755'
      become: true

    - name: Ensure Nomad service unit is overridden with custom ExecStartPost
      ansible.builtin.blockinfile:
        path: '/etc/systemd/system/nomad.service.d/override.conf'
        create: true
        marker: '# {mark} ANSIBLE MANAGED BLOCK: ExecStartPost'
        block: |
          [Service]
          ExecStartPost=/opt/nomad-execstartpost.sh
        mode: '0644'
      become: true

- name: Install ssm deploy command scripts
  hosts: bastion

  tasks:
    - name: Ensure /opt/actions directory
      ansible.builtin.file:
        path: /opt/actions
        state: directory
        mode: '0755'
      become: true

    - name: Template ssm deploy command scripts
      ansible.builtin.template:
        dest: '/opt/actions/{{ item }}'
        src: './templates/nomad/actions/{{ item }}.j2'
        mode: '0755'
      become: true
      loop:
        - deploy.sh
