---
- name: systemd-resolved config for using consul as dns
  hosts: all

  tasks:
    - name: ensure /etc/systemd/resolved.conf.d
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
      become: true

    - name: place consul config in /etc/systemd/resolved.conf.d
      ansible.builtin.template:
        src: ./templates/resolved.j2
        dest: /etc/systemd/resolved.conf.d/consul.conf
      become: true

    - name: reload systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
      become: true
