---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install nginx proxy config
  ansible.builtin.template:
    src: '../templates/nginx-proxy.j2'
    dest: '/etc/nginx/sites-available/default'
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure nginx starts after consul
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/nginx.service
    regexp: '^After='
    line: 'After=network-online.target consul.service'
    backrefs: yes
  become: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
