---
- name: Set fact on consul node registration token
  ansible.builtin.set_fact:
    consul_node_registration_token: "{{ lookup('amazon.aws.aws_secret', '/' ~ ENVIRONMENT ~ '/consul/node_registration', region=aws_region) }}"

- name: Create acl.hcl file
  ansible.builtin.copy:
    content: |
      acl {
        enabled = true
        default_policy = "deny"
        tokens {
          default = "{{ lookup('amazon.aws.aws_secret', '/' ~ ENVIRONMENT ~ '/consul/node_registration', region=aws_region) }}"
        }
      }
    dest: /etc/consul.d/acl.hcl
    owner: consul
    group: consul
    mode: '0600'
  become: true
  notify:
    - Restart consul

- name: Copy vault server cert
  ansible.builtin.copy:
    dest: '/etc/vault.d/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-server.pem'
    src: '../../base/files/vault/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-server.pem'
    mode: '0644'
  become: true

- name: Copy vault server key
  ansible.builtin.copy:
    dest: '/etc/vault.d/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-server-key.pem'
    src: '../../base/files/vault/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-server-key.pem'
    mode: '0644'
  become: true

- name: Set facts for client vault.hcl templating
  ansible.builtin.set_fact:
    vault_node_id: "{{ ENVIRONMENT }}-{{ role }}-{{ ansible_default_ipv4.address | replace('.', '-') }}"
    vault_agent_token: "{{ lookup('amazon.aws.aws_secret', '/' ~ ENVIRONMENT ~ '/vault/agent_token', region=aws_region) }}"
    consul_node_registration_token: "{{ lookup('amazon.aws.aws_secret', '/' ~ ENVIRONMENT ~ '/consul/vault_server_registration', region=aws_region) }}"
    app_role_list:
      - proxy
      - billing
      - history
      - shop
      - bot

- name: Get role_id for AppRole
  hashivault_approle_role_id:
    name: '{{ item }}'
    token: '{{ vault_agent_token }}'
    url: 'https://vault.service.consul:8200'
    verify: false
  register: role_id_result
  loop: '{{ app_role_list }}'

- name: Write all role ids to individual files
  ansible.builtin.copy:
    content: |
      {{ item.data.role_id }}
    dest: '/etc/vault.d/role_ids_{{ item.item }}'
    mode: '0600'
  loop: '{{ role_id_result.results }}'
  become: true

- name: Create or update the vault secret for each app role
  hashivault_approle_role_secret:
    name: '{{ item.item }}'
    token: '{{ vault_agent_token }}'
    url: 'https://vault.service.consul:8200'
    authtype: token
    verify: false
  register: role_secret_result
  loop: '{{ role_id_result.results }}'

- name: Write all secret ids to individual files
  ansible.builtin.copy:
    content: |
      {{ item.data.secret_id }}
    dest: '/etc/vault.d/secret_ids_{{ item.item.item }}'
    mode: '0600'
  loop: '{{ role_secret_result.results }}'
  become: true

- name: Copy vault agent cert
  ansible.builtin.copy:
    dest: '/etc/vault.d/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-agent.pem'
    src: '../../base/files/vault/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-agent.pem'
    mode: '0644'
  become: true

- name: Copy vault agent key
  ansible.builtin.copy:
    dest: '/etc/vault.d/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-agent-key.pem'
    src: '../../base/files/vault/{{ ENVIRONMENT }}-{{ CONSUL_DOMAIN }}-agent-key.pem'
    mode: '0644'
  become: true

- name: Template vault.hcl with client config
  ansible.builtin.template:
    src: ./templates/vault/client.hcl.j2
    dest: /etc/vault.d/vault.hcl
    mode: '0644'
  become: true

- name: Create vault agent systemd unit file
  ansible.builtin.copy:
    dest: /etc/systemd/system/vault-agent.service
    content: |
      [Unit]
      Description=Vault Agent
      Requires=network-online.target
      After=network-online.target
      [Service]
      EnvironmentFile=/etc/vault.d/vault.env
      ExecStart=/usr/bin/vault agent -config=/etc/vault.d/vault.hcl
      Restart=on-failure
      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

- name: Enable and start vault agent systemd service
  ansible.builtin.systemd:
    name: vault-agent
    enabled: true
    state: restarted
  become: true
