- name: Install service based on instance role
  hosts: all

  vars:
    role: eliza

    git_repo: 'git@github.com:Use-Prism/{{ role }}.git'
    srv_base_dir: /srv/{{ role }}
    git_repo_dest: '{{ srv_base_dir }}/{{ role }}.git'
    checkout_dest: '{{ srv_base_dir }}/{{ role }}'
    owner: '{{ role }}'
    group: '{{ role }}'
    key_file: /home/{{ role }}/.ssh/{{ role }}-checkout.pem

  tasks:
    - amazon.aws.ec2_metadata_facts:
      register: meta

    - set_fact:
        role: '{{ meta.ansible_facts.ansible_ec2_tags_instance_Role }}'

    - import_tasks: ./tasks/eliza-set-facts.yml

    - name: Remove eliza upstream from consul kv store
      community.general.consul_kv:
        key: eliza/agents/{{ customer_id }}
        # value: '{{ ansible_default_ipv4.address }}:3000'
        state: absent

    - name: Shut down docker-compose
      ansible.builtin.shell: docker-compose down
      args:
        chdir: /home/eliza
      become: true

    - import_tasks: ./tasks/pull-eliza-once.yml
