- name: execute a playbook based on instance role
  hosts: all

  vars:
    CONSUL_DOMAIN: 'consul'
    AWS_ACCOUNT: '686255952373'
    instance_roles:
      - nginx
      - eliza

  tasks:
    - amazon.aws.ec2_metadata_facts:
      register: meta

    - debug:
        var: meta

    # this needs metadata access for the instance set in launch template!!
    - set_fact:
        role: '{{ meta.ansible_facts.ansible_ec2_tags_instance_Role }}'
        AWS_REGION: '{{ meta.ansible_facts.ansible_ec2_instance_identity_document_region }}'

    # 0 - run once

    - name: Check for one‑time run flag
      ansible.builtin.stat:
        path: /tmp/ansible_pull_once.flag
      register: run_once_flag

    - import_tasks: ./tasks/pull-once.yml
      when: not run_once_flag.stat.exists

    - name: Create one‑time run flag
      ansible.builtin.copy:
        content: 'Ran on {{ ansible_date_time.iso8601 }}'
        dest: /tmp/ansible_pull_once.flag
      when: not run_once_flag.stat.exists

    # 1 - always run

    - import_tasks: ./tasks/user-accounts.yml
    - import_tasks: ./tasks/get-instance-tag-values.yml

    # 2 - run based on instance role

    - import_tasks: ./tasks/pull-eliza.yml
      when: role == 'eliza'

    - import_tasks: ./tasks/pull-bastion.yml
      when: role == 'bastion'

    # - import_tasks: ./tasks/pull-nomad.yml
    #   when: role == 'bastion'

    # 3 - run once based on instance role

    # 3.1 - role: bastion

    - name: Check for bastion one‑time run flag
      ansible.builtin.stat:
        path: /tmp/ansible_pull_once_bastion.flag
      register: run_once_flag_bastion

    - import_tasks: ./tasks/pull-bastion-once.yml
      when: role == 'bastion' and not run_once_flag_bastion.stat.exists

    - name: Create bastion one‑time run flag
      ansible.builtin.copy:
        content: 'Ran on {{ ansible_date_time.iso8601 }}'
        dest: /tmp/ansible_pull_once_bastion.flag
      when: not run_once_flag_bastion.stat.exists

    # 3.2 - Hashistack one‑time run tasks
    #     - Doesn't run repeatedly to save on AWS Secrets Manager costs

    # - name: Check for consul_all one‑time run flag
    #   ansible.builtin.stat:
    #     path: /tmp/ansible_pull_once_consul_all.flag
    #   register: run_once_flag_consul_all

    # - name: Import consul client specific tasks
    #   import_tasks: ./tasks/pull-once-consul-all.yml
    #   when: not run_once_flag_consul_all.stat.exists

    # - name: Create consul_all one‑time run flag
    #   ansible.builtin.copy:
    #     content: 'Ran on {{ ansible_date_time.iso8601 }}'
    #     dest: /tmp/ansible_pull_once_consul_all.flag
    #   when: not run_once_flag_consul_all.stat.exists

    - name: Check for consul_client one‑time run flag
      ansible.builtin.stat:
        path: /tmp/ansible_pull_once_consul_client.flag
      register: run_once_flag_consul_client

    - name: Import consul client specific tasks
      import_tasks: ./tasks/pull-once-consul-clients.yml
      when: role in ['nginx', 'eliza'] and not run_once_flag_consul_client.stat.exists

    - name: Create consul_client one‑time run flag
      ansible.builtin.copy:
        content: 'Ran on {{ ansible_date_time.iso8601 }}'
        dest: /tmp/ansible_pull_once_consul_client.flag
      when: not run_once_flag_consul_client.stat.exists

  handlers:
    - name: Restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        enabled: yes
      become: true

    - name: Restart nomad
      ansible.builtin.systemd:
        name: nomad
        state: restarted
        enabled: yes
      become: true

- name: execute a playbook based on instance role
  hosts: all

  tasks:
    # 4 - clients

    # 4.1 - client: eliza

    - name: Check for eliza one‑time run flag
      ansible.builtin.stat:
        path: /tmp/ansible_pull_once_eliza.flag
      register: run_once_flag_eliza

    - import_tasks: ./tasks/pull-eliza-once.yml
      when: role == 'eliza' and not run_once_flag_eliza.stat.exists

    - name: Create eliza one‑time run flag
      ansible.builtin.copy:
        content: 'Ran on {{ ansible_date_time.iso8601 }}'
        dest: /tmp/ansible_pull_once_eliza.flag
      when: not run_once_flag_eliza.stat.exists

  handlers:
    - name: Restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        enabled: yes
      become: true

    - name: Restart nomad
      ansible.builtin.systemd:
        name: nomad
        state: restarted
        enabled: yes
      become: true
