---
- name: copy consul ca cert
  ansible.builtin.copy:
    dest: '/etc/consul.d/{{ ENVIRONMENT }}-consul-agent-ca.pem'
    src: './files/consul/{{ ENVIRONMENT }}-consul-agent-ca.pem'
  become: true

- name: template consul.hcl
  ansible.builtin.template:
    src: ./templates/consul/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  become: true
  vars:
    CONSUL_KEY: "{{ lookup('file', './files/consul/{{ ENVIRONMENT }}-consul-gossip.key') }}"

- name: create resolved.conf.d
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
  become: true

- name: template consul resolved config
  ansible.builtin.template:
    src: ./templates/resolved.conf.d/consul.conf.j2
    dest: /etc/systemd/resolved.conf.d/consul.conf
  become: true

- name: template main resolved.conf
  ansible.builtin.template:
    src: ./templates/resolved.conf.d/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  become: true
