---
- name: copy nomad ca
  ansible.builtin.copy:
    dest: '/etc/nomad.d/{{ ENVIRONMENT }}-ca.pem'
    src: './files/nomad/{{ ENVIRONMENT }}-ca.pem'
  become: true

- name: template nomad.hcl
  ansible.builtin.template:
    src: ./templates/nomad/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
  become: true
  vars:
    CONSUL_KEY: 'defined-on-bastion-first-run'
