- name: Test
  hosts: nginx

  vars:
    CONSUL_DOMAIN: 'consul'
    ENVIRONMENT: 'prod1'
    AWS_REGION: 'eu-central-1'

  tasks:
    - name: Get the vault token from aws secrets manager
      ansible.builtin.set_fact:
        vault_agent_token: '{{ lookup("amazon.aws.aws_secret", "/" + ENVIRONMENT + "/vault/agent_token", region=AWS_REGION) }}'
