- name: Vault server tasks
  hosts: bastion

  vars:
    CONSUL_DOMAIN: 'consul'
    ENVIRONMENT: 'prod1'
    AWS_REGION: 'eu-central-1'
    instance_roles:
      - nginx
      - eliza
    aws_account_id: '686255952373'

  tasks:
    - name: Get the vault token from aws secrets manager
      ansible.builtin.set_fact:
        vault_root_token: "{{ lookup('amazon.aws.aws_secret', '/' + ENVIRONMENT + '/vault/vault_root_token', region=AWS_REGION) }}"
        bootstrap_acl_token: "{{ lookup('amazon.aws.aws_secret', '/' + ENVIRONMENT + '/consul/acl_token', region=AWS_REGION) }}"

    # start Vault AWS Auth method

    - name: Enable AWS auth method on vault
      hashivault_auth_method:
        method_type: aws
        token: '{{ vault_root_token }}'

    - name: Configure AWS auth method
      hashivault_aws_auth_config:
        token: '{{ vault_root_token }}'

    - name: Create the Consul ACL policy for client agents
      community.general.consul_policy:
        name: 'consul-agent-{{ item }}'
        rules: |
          node_prefix "{{ ENVIRONMENT }}-{{ item }}-" {
            policy = "write"
          }
          service_prefix "" {
            policy = "read"
          }
        token: '{{ bootstrap_acl_token }}'
      loop: '{{ instance_roles }}'

    - name: Create Consul Agent policy
      hashivault_policy:
        name: 'consul-agent-{{ item }}'
        rules: |
          path "consul/creds/consul-agent-{{ item }}" {
            capabilities = ["read"]
          }
        token: '{{ vault_root_token }}'
      loop: '{{ instance_roles }}'

    - name: Create the AWS role for Consul Agent
      hashivault_aws_auth_role:
        name: consul-agent-{{ item }}
        auth_type: iam
        bound_iam_principal_arn: arn:aws:iam::{{ aws_account_id }}:role/{{ ENVIRONMENT }}-{{ item }}
        policies:
          - consul-agent-{{ item }}
        token: '{{ vault_root_token }}'
      loop: '{{ instance_roles }}'

    - name: Configure the secret engine
      hashivault_secret_engine:
        name: consul
        backend: consul
        token: '{{ vault_root_token }}'

    - name: Configure the consul secret engine
      hashivault_consul_secret_engine_config:
        consul_address: consul.service.consul:8500
        scheme: http
        consul_token: '{{ bootstrap_acl_token }}'
        token: '{{ vault_root_token }}'

    - name: Create the consul-agent role
      hashivault_consul_secret_engine_role:
        name: 'consul-agent-{{ item }}'
        policies:
          - consul-agent-{{ item }}
        token: '{{ vault_root_token }}'
      loop: '{{ instance_roles }}'
# end Vault AWS Auth method
