- name: Vault server tasks
  hosts: bastion

  tasks:
    - name: Get the vault token from aws secrets manager
      ansible.builtin.set_fact:
        vault_root_token: "{{ lookup('amazon.aws.aws_secret', '/' + ENVIRONMENT + '/vault/vault_root_token', region=AWS_REGION) }}"
        bootstrap_acl_secret: "{{ lookup('amazon.aws.aws_secret', '/' + ENVIRONMENT + '/consul/acl_token', region=AWS_REGION) }}"

    - name: Create consul application token for eliza-proxy
      community.general.consul_policy:
        token: '{{ bootstrap_acl_secret }}'
        name: 'eliza-proxy-token'
        rules: |
          key_prefix "eliza" {
            policy = "read"
          }

    - name: Create consul application token for eliza-proxy
      community.general.consul_token:
        policies:
          - name: eliza-proxy-token
        description: 'App token for eliza-proxy'
        token: '{{ bootstrap_acl_secret }}'
