---
- name: Install docker-compose
  ansible.builtin.package:
    name: docker-compose
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Ensure user is part of the docker group
  ansible.builtin.user:
    name: '{{ role }}'
    groups: docker
  become: true
