- name: fetch cni plugin
  ansible.builtin.get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
    dest: /tmp/cni-plugins.tgz
  become: true

- name: mkdir /opt/cni/bin
  file:
    path: /opt/cni/bin
    state: directory
  become: true

- name: install cni plugin
  ansible.builtin.unarchive:
    src: /tmp/cni-plugins.tgz
    dest: /opt/cni/bin
    remote_src: yes
  become: true

- name: modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter
  become: true

- name: sysctl netfilter bridge network via iptables
  ansible.builtin.sysctl:
    name: '{{ item }}'
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  become: true