---
- name: Debug service variable
  ansible.builtin.debug:
    var: service

- name: Ensure hosting user
  ansible.builtin.user:
    name: '{{ owner }}-{{ service.service_name }}'
    system: true
  become: true

# community.general.yarn is broken for yarn 2
# - name: install packages with yarn
#   community.general.yarn:
#     executable: yarnpkg
#     path: '{{ checkout_dest }}'
#   become: true

# - name: install packages with yarn
#   ansible.builtin.command:
#     cmd: yarnpkg
#     chdir: '{{ checkout_dest }}'
#   become: true

# revert back to npm for now
- name: Install npm packages
  community.general.npm:
    path: '{{ checkout_dest }}/{{ service.working_directory }}'
    # production: yes
    unsafe_perm: yes
  become: true

- name: Ensure service hosting directory ownership
  ansible.builtin.file:
    path: '{{ checkout_dest }}/{{ service.working_directory }}'
    owner: '{{ owner }}-{{ service.service_name }}'
    recurse: yes
  become: true

- name: Install systemd unit
  ansible.builtin.template:
    src: '../templates/{{ role }}.service.j2'
    dest: '/lib/systemd/system/{{ owner }}-{{ service.service_name }}.service'
    owner: root
    group: root
    mode: 0640
  become: true

- name: Enable service on systemd
  ansible.builtin.service:
    name: '{{ owner }}-{{ service.service_name }}'
    enabled: yes
    daemon_reload: yes
  become: true

- name: Start service on systemd
  ansible.builtin.service:
    name: '{{ owner }}-{{ service.service_name }}'
    state: restarted
  become: true
  tags: packer-skip
