---
ENVIRONMENT: test1
NOMAD_ENV: '{{ ENVIRONMENT }}'
DOMAIN: prism1.click
ELIZA_DEPLOY_REF: main
AWS_ACCOUNT: 686255952373
AWS_REGION: eu-central-1
CONSUL_DATACENTER: '{{ AWS_REGION }}-{{ ENVIRONMENT }}'
CONSUL_SERVER_COUNT: 1
CONSUL_DOMAIN: consul
GIT_REF: 'latest-{{ ENVIRONMENT }}'
ansible_user: ubuntu
